// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  identity: __t.string(),
  name: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  health: __t.f32(),
  hunger: __t.f32(),
  stamina: __t.f32(),
  region: __t.string(),
  connected: __t.bool(),
  lastSeen: __t.f64(),
});
