// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  keys: __t.string(),
  hasMoveTarget: __t.bool(),
  moveTargetX: __t.f32(),
  moveTargetY: __t.f32(),
  hasPointer: __t.bool(),
  pointerX: __t.f32(),
  pointerY: __t.f32(),
  buildActive: __t.bool(),
  buildSelected: __t.string(),
  buildRotation: __t.i32(),
  mode: __t.string(),
  inventoryOpen: __t.bool(),
  updatedAt: __t.f64(),
});
