FROM heroiclabs/nakama-pluginbuilder:3.22.0 AS builder
WORKDIR /workspace

COPY services/nakama/go.mod services/nakama/go.sum ./
RUN go mod download

COPY services/nakama/*.go ./

RUN go build --trimpath --buildmode=plugin -o /backend.so .

FROM heroiclabs/nakama:3.22.0
COPY --from=builder /backend.so /nakama/data/modules/backend.so
COPY infra/docker/nakama.yml /nakama/data/local.yml
