FROM golang:1.26 AS builder
WORKDIR /workspace

COPY go.mod go.sum ./
RUN go mod download

COPY internal ./internal
COPY proto ./proto
COPY services/worldd ./services/worldd

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/worldd ./services/worldd

FROM gcr.io/distroless/base-debian12
COPY --from=builder /out/worldd /usr/local/bin/worldd
ENTRYPOINT ["/usr/local/bin/worldd"]
