export const CONFIG = {
  baseAspect: 16 / 9,
  gatherRange: 1.1,
  gatherCooldown: 0.6,
  messageDuration: 1.6,
  messageMax: 3,
  baseTileSize: 32,
  resourceRespawn: {
    berrybush: { min: 70, max: 130 },
  },
  paths: {
    wearThreshold: 8,
    maxWear: 22,
    decay: 0.12,
  },
};

export const BUILDINGS = {
  campfire: {
    cost: { wood: 2 },
    radius: 0.35,
    footprint: { w: 1, h: 1 },
    baseRadius: 0.35,
    footprintRadius: 0.6,
    unlockLevel: 1,
    canopy: false,
    category: "utility",
    solid: false,
    maxLevel: 0,
    supportsUpper: false,
  },
  shelter: {
    cost: { wood: 6, stone: 2 },
    size: 0.9,
    footprint: { w: 2, h: 2 },
    baseSize: { w: 0.9, h: 0.5 },
    roof: { w: 1.2, h: 0.85, offsetY: -0.18 },
    footprintRadius: 0.8,
    unlockLevel: 2,
    canopy: true,
    category: "housing",
    solid: false,
  },
  lean_to: {
    cost: { wood: 4, planks: 2 },
    footprint: { w: 2, h: 1 },
    baseSize: { w: 0.9, h: 0.4 },
    roof: { w: 1.6, h: 0.85, offsetY: -0.12 },
    footprintRadius: 0.6,
    unlockLevel: 2,
    canopy: true,
    category: "housing",
    solid: false,
  },
  workbench: {
    cost: { wood: 4, stone: 2 },
    footprint: { w: 2, h: 1 },
    baseSize: { w: 0.7, h: 0.35 },
    footprintRadius: 0.6,
    unlockLevel: 3,
    canopy: false,
    category: "utility",
    solid: false,
    supportsUpper: false,
  },
  hut: {
    cost: { planks: 6, stone: 4, hide: 2 },
    footprint: { w: 3, h: 2 },
    baseSize: { w: 1.1, h: 0.65 },
    roof: { w: 1.6, h: 1.1, offsetY: -0.25 },
    footprintRadius: 1.05,
    unlockLevel: 4,
    canopy: true,
    category: "housing",
    solid: false,
  },
  storage_crate: {
    cost: { planks: 4, hide: 1 },
    footprint: { w: 1, h: 1 },
    baseSize: { w: 0.6, h: 0.4 },
    footprintRadius: 0.4,
    unlockLevel: 2,
    canopy: false,
    category: "utility",
    solid: false,
    maxLevel: 0,
    supportsUpper: false,
  },
  wood_floor: {
    cost: { planks: 2 },
    footprint: { w: 1, h: 1 },
    baseSize: { w: 0.95, h: 0.18 },
    footprintRadius: 0,
    spacing: 0,
    unlockLevel: 1,
    canopy: false,
    category: "housing",
    solid: false,
  },
  wood_wall: {
    cost: { wood: 3 },
    footprint: { w: 1, h: 1 },
    baseSize: { w: 0.9, h: 0.5 },
    footprintRadius: 0,
    spacing: 0,
    unlockLevel: 2,
    canopy: false,
    category: "defense",
    solid: true,
  },
  wood_gate: {
    cost: { planks: 3 },
    footprint: { w: 1, h: 1 },
    baseSize: { w: 0.9, h: 0.5 },
    footprintRadius: 0,
    spacing: 0,
    unlockLevel: 3,
    canopy: false,
    category: "defense",
    toggleable: true,
    solid: true,
  },
};

export const ITEMS = {
  wood: { name: "Wood", maxStack: 32 },
  stone: { name: "Stone", maxStack: 32 },
  berry: { name: "Berries", maxStack: 16, edible: { hunger: 18, stamina: 6 } },
  planks: { name: "Planks", maxStack: 32 },
  meat: { name: "Meat", maxStack: 8, edible: { hunger: 28, stamina: 10, health: 4 } },
  cooked_meat: { name: "Cooked Meat", maxStack: 8, edible: { hunger: 40, stamina: 14, health: 10 } },
  hide: { name: "Hide", maxStack: 12 },
  campfire: { name: "Campfire", maxStack: 16 },
  shelter: { name: "Shelter", maxStack: 8 },
  lean_to: { name: "Lean-to", maxStack: 8 },
  workbench: { name: "Workbench", maxStack: 8 },
  hut: { name: "Hut", maxStack: 4 },
  stone_axe: { name: "Stone Axe", maxStack: 1 },
  stone_pick: { name: "Stone Pick", maxStack: 1 },
  stone_spear: { name: "Stone Spear", maxStack: 1 },
  reinforced_axe: { name: "Reinforced Axe", maxStack: 1 },
  reinforced_pick: { name: "Reinforced Pick", maxStack: 1 },
  reinforced_spear: { name: "Reinforced Spear", maxStack: 1 },
  hide_armor: { name: "Hide Armor", maxStack: 1 },
  backpack: { name: "Backpack", maxStack: 1 },
  wood_wall: { name: "Wood Wall", maxStack: 20 },
  wood_gate: { name: "Wood Gate", maxStack: 12 },
  storage_crate: { name: "Storage Crate", maxStack: 6 },
  wood_floor: { name: "Wood Floor", maxStack: 24 },
};

export const CRAFTING_RECIPES = [
  {
    pattern: ["stone", "stone", "wood", "wood"],
    output: { id: "stone_axe", count: 1 },
    unlockLevel: 3,
    requiresStructure: "workbench",
  },
  {
    pattern: ["stone", "stone", "stone", "wood"],
    output: { id: "stone_pick", count: 1 },
    unlockLevel: 3,
    requiresStructure: "workbench",
  },
  {
    pattern: ["wood", "stone", "wood", "stone"],
    output: { id: "stone_spear", count: 1 },
    unlockLevel: 3,
    requiresStructure: "workbench",
  },
  {
    pattern: ["hide", "planks", "hide", "planks"],
    output: { id: "hide_armor", count: 1 },
    unlockLevel: 4,
    requiresStructure: "workbench",
  },
  {
    pattern: ["stone", "planks", "planks", "wood"],
    output: { id: "reinforced_axe", count: 1 },
    unlockLevel: 4,
    requiresStructure: "workbench",
  },
  {
    pattern: ["planks", "stone", "planks", "stone"],
    output: { id: "reinforced_pick", count: 1 },
    unlockLevel: 4,
    requiresStructure: "workbench",
  },
  {
    pattern: ["stone", "hide", "planks", "planks"],
    output: { id: "reinforced_spear", count: 1 },
    unlockLevel: 4,
    requiresStructure: "workbench",
  },
  {
    pattern: ["wood", "wood", "wood", "stone"],
    output: { id: "backpack", count: 1 },
    unlockLevel: 3,
    requiresStructure: "workbench",
  },
  {
    pattern: ["wood", "wood", "wood", "wood"],
    output: { id: "planks", count: 2 },
    unlockLevel: 2,
  },
];

export const PROGRESSION = {
  baseXpToLevel: 20,
  xpGrowth: 1.4,
  xp: {
    gather: 3,
    build: 6,
    craft: 5,
    cook: 4,
    forage: 2,
    combat: 6,
  },
};

export const CREATURES = {
  boar: {
    maxHealth: 28,
    speed: 1.6,
    aggroRange: 3.4,
    attackRange: 0.8,
    damage: 8,
    diet: "herbivore",
    predators: ["wolf"],
    nocturnal: false,
    nightSpeedMultiplier: 1.15,
    nightAggroMultiplier: 1.25,
    hungerThreshold: 0.55,
    thirstThreshold: 0.45,
    restThreshold: 0.28,
    criticalHunger: 0.22,
    criticalThirst: 0.2,
    foodSearchRange: 6,
    waterSearchRange: 7,
    fleeRange: 4.6,
    homeRange: 6,
    packRadius: 3.5,
    trailSpacing: 0.55,
    scentRange: 5.5,
    avoidCarcassRange: 3.5,
    carcassNutrition: 46,
    carcassTtl: 80,
    grazeGain: 12,
    berryGain: 34,
    drinkGain: 38,
    needs: {
      maxHunger: 100,
      maxThirst: 90,
      maxEnergy: 90,
      hungerDrain: 0.55,
      thirstDrain: 0.5,
      energyDrain: 0.65,
      energyRegen: 0.95,
    },
    xp: 10,
    drops: [
      { id: "meat", min: 1, max: 2 },
      { id: "hide", min: 0, max: 1 },
    ],
  },
  wolf: {
    maxHealth: 22,
    speed: 2.2,
    aggroRange: 4.2,
    attackRange: 0.9,
    damage: 6,
    diet: "carnivore",
    prey: ["boar"],
    fearPlayer: false,
    nocturnal: true,
    hungerThreshold: 0.6,
    thirstThreshold: 0.45,
    restThreshold: 0.22,
    criticalHunger: 0.25,
    criticalThirst: 0.2,
    huntRange: 7.5,
    huntHungerThreshold: 0.65,
    waterSearchRange: 8,
    homeRange: 7,
    packRadius: 4.6,
    denType: "wolf_den",
    denSearchRange: 10,
    scentRange: 7.5,
    trailSpacing: 0.6,
    defendDen: true,
    denDefenseRange: 4.6,
    carcassNutrition: 38,
    carcassTtl: 70,
    meatGain: 40,
    needs: {
      maxHunger: 110,
      maxThirst: 100,
      maxEnergy: 100,
      hungerDrain: 0.65,
      thirstDrain: 0.6,
      energyDrain: 0.85,
      energyRegen: 0.9,
    },
    nightSpeedMultiplier: 1.25,
    nightAggroMultiplier: 1.35,
    xp: 8,
    drops: [
      { id: "meat", min: 1, max: 1 },
      { id: "hide", min: 1, max: 2 },
    ],
  },
};

export const QUESTS = [
  {
    id: "gather-wood",
    type: "gather",
    item: "wood",
    target: 6,
    label: "Gather 6 wood",
    rewardXp: 8,
  },
  {
    id: "gather-stone",
    type: "gather",
    item: "stone",
    target: 4,
    label: "Gather 4 stone",
    rewardXp: 8,
  },
  {
    id: "forage-berries",
    type: "gather",
    item: "berry",
    target: 3,
    label: "Forage 3 berries",
    rewardXp: 6,
  },
  {
    id: "craft-planks",
    type: "craft",
    item: "planks",
    target: 2,
    label: "Craft planks",
    rewardXp: 10,
  },
  {
    id: "build-campfire",
    type: "build",
    item: "campfire",
    target: 1,
    label: "Build a campfire",
    rewardXp: 12,
  },
  {
    id: "build-shelter",
    type: "build",
    item: "shelter",
    target: 1,
    label: "Build a shelter",
    rewardXp: 14,
  },
  {
    id: "build-lean-to",
    type: "build",
    item: "lean_to",
    target: 1,
    label: "Build a lean-to",
    rewardXp: 10,
  },
  {
    id: "hunt-boar",
    type: "gather",
    item: "meat",
    target: 2,
    label: "Hunt boar (loot meat)",
    rewardXp: 16,
  },
  {
    id: "cook-meat",
    type: "cook",
    item: "cooked_meat",
    target: 1,
    label: "Cook meat at a campfire",
    rewardXp: 10,
  },
  {
    id: "craft-spear",
    type: "craft",
    item: "stone_spear",
    target: 1,
    label: "Craft a spear",
    rewardXp: 12,
  },
  {
    id: "craft-armor",
    type: "craft",
    item: "hide_armor",
    target: 1,
    label: "Craft hide armor",
    rewardXp: 12,
  },
  {
    id: "build-wall",
    type: "build",
    item: "wood_wall",
    target: 2,
    label: "Build 2 walls",
    rewardXp: 10,
  },
  {
    id: "build-crate",
    type: "build",
    item: "storage_crate",
    target: 1,
    label: "Build a storage crate",
    rewardXp: 10,
  },
  {
    id: "hunt-wolf",
    type: "defeat",
    item: "wolf",
    target: 1,
    label: "Defeat a wolf",
    rewardXp: 14,
  },
];

export const PALETTE = {
  water: "#9cb7c5",
  sand: "#d9c9a5",
  grass: "#a6b98f",
  dirt: "#b4987a",
  rock: "#8c8f92",
};
